config/routes.rb
Rails.application.routes.draw do
  
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  get '/logout', to: 'sessions#logout', as: 'logout'

  get '/signin', to: 'sessions#sign_in_form', as: 'sign_in_form'

  post '/signin', to: 'sessions#signin', as: 'signin'

  get '/user/:user_id/proyecto/:proyecto_id/questions/:id/answer/new', to: 'answers#new', as: 'show_answer'
  
  get '/collaboration/collaboration', as: 'collaboration'

  get '/proyecto/:id/collaboration/collaboration', to: 'collaboration#collaboration', as: 'show_collaboration_space'

  get '/proyecto/:proyecto_id/collaboration/collaboration', to:'collaboration#collaboration', as: 'back_collaboration_space'
  get '/user/:user_id/proyecto/:proyecto_id/questions/:id/collaboration/collaboration', to: 'collaboration#answers_question', as: 'show_answers_question'

  get '/proyecto/:id/users/show', to: 'postulations#create', as: 'request'

  get '/proyectos/new', to: 'proyectos#new', as: 'new_project'
 
  get '/proyectos/:id', to: 'proyectos#show', as: 'description_project'

   get '/proyecto/:id/users/:user_id/practicantes/show', to: 'postulations#update', as: 'update_request'

  get '/proyecto/:id/practicantes/show', to: 'practicantes#show', as: 'show_participantes_proyecto'

  get '/user/:id/perfil/practicante', to: 'practicantes#profile', as: 'perfil_pract'

  get '/proyecto/:id/practicantes/show', to: 'practicantes#back', as: 'back_participantes_proyecto'

  get '/question/:id/collaboration/collaboration', to: 'collaboration#download_file', as: 'download_file'

  
  resources :users
  resources :skills
  resources :proyectos
  resources :answers
 
  
  resources :proyectos do
    resources :questions
  end

  resources :questions do
      resources :answers
    end

  root 'sessions#home'
  
  Letscode::Application.routes.draw do
   resources :questions, only: [:index, :new, :create, :destroy]
  end
  

end

app/controllers/collaboration_controller.rb
class CollaborationController < ApplicationController
	
	def collaboration
	  @questions = Question.where(proyecto_id: params[:id]).paginate(page: params[:page], per_page: 3)
	  @proyecto = Proyecto.find(params[:id])
	  @users = User.all
	end

	def answers_question
		@user = User.find(params[:user_id])
	  @answers = Question.find(params[:id]).answers
	  @question = Question.find(params[:id])
	  @proyecto = Proyecto.find(params[:proyecto_id])
	  render 'collaboration/answers'
	end

	def download_file
	  @question = Question.find(params[:id])
	  send_file(@question.attachment.path,
	        # :type => 'application/pdf',
	        # :disposition => 'attachment',
	        # :url_based_filename => true)
	        :disposition => 'attachment',
	        :url_based_filename => false)
  end
end

app/views/collaboration/answers.html.erb
<div class="row col-md-6 col-md-offset-3">
  <p id="notice"><%= notice %></p>

    <div class="status row">
    	<h2><%= @user.name %> <small><%= @user.last_name %></small></h2>
    </div>

    <div>
      <h1><small><%= @question.title %></small></h1>
      <h5><small><%= @question.question %></small></h5>
      <h6><small>Posted by <%= @user.name %> at <%= @question.created_at.to_formatted_s(:long) %> </small></h6>
    </div>

    <div class="status row">
      <h4><%= @answers.count%> Comment:</h4>
    </div>
    <% @answers.each do |answer| %>
      <div class="status row">
          <div class="span7">
          	<strong id="span7"><small><%= answer.responder.name %> said...</small></strong>
    		    <p><small> <%= answer.answer %></small></p>
    		    <h6><small> <%= answer.created_at.to_formatted_s(:long)%></small></h6>
          </div>
      </div>
    <% end %>

    <p><small><u><%= link_to "Post a comment", show_answer_path(@user, @proyecto, @question) %></u></small> | <%= link_to "Back", show_collaboration_space_path(@proyecto) %></p>
</div>

app/views/collaboration/collaboration.html.erb
<div class="row col-md-6 col-md-offset-3">
    <div class="page-header">
      <h1>Collaboration Space</h1>
    </div>

    <% if @errors %>
      <p><%= @errors %></p>
    <% end %>
    <div id="colabzone"> 

      <% @posts_discussion = false %>
      <% @questions.each do |question| %>
        <% @users.each do |user| %>
        <% if question.user_id == user.id && question.question_type == "discussion" %>
      		<% if @posts_discussion == false %>
              <h3>Discussions</h3>
              <% @posts_discussion = true %>
            <% end %>
          <div class="status row">
            <div class="span7">
              <strong><%= "#{user.name} #{user.last_name} " %></strong><small>says:</small>
              <p><strong><small><%= question.title %></small></strong></p>
              <p><small><em><%= question.question %></em></small></p>
              <div class="meta">
                <p><small><%= link_to time_ago_in_words(question.created_at) + " ago", show_answers_question_path(user, @proyecto, question) %>
                <% if question.attachment_url %>
                  <%= link_to "Download", download_file_path(question), class: 'btn btn btn-info btn-xs' %>
                <% end %>
                </small>
                <span>
      	          <%= link_to 'Reply', show_answer_path(user, @proyecto, question), class: 'btn btn btn-primary btn-xs' %>
                </span>
                </p>
              </div>
            </div>
          </div>
        <% end %>
        <% end %>
      <% end %>

      <% @posts_resource = false %>
      <% @questions.each do |question| %>
        <% @users.each do |user| %>
          <% if question.user_id == user.id && question.question_type == "resource" %>
            <% if @posts_resource == false %>
              <h3>Resources</h3>
              <% @posts_resource = true %>
            <% end %>
            <div class="status row">
              <div class="span7">
                  <strong><%= "#{user.name} #{user.last_name} " %></strong><small>says:</small>
                  <p><strong><small><%= question.title %></small></strong></p>
                  <p><small><em><%= question.question %></em></small></p>
                  <div class="meta">
                    <p><small><%= link_to time_ago_in_words(question.created_at) + " ago", show_answers_question_path(user, @proyecto, question) %>
                    <% if question.attachment_url %>
                      <%= link_to "Download", download_file_path(question), class: 'btn btn btn-info btn-xs' %>
                    <% end %>
                    </small>
                    <span>
                      <%= link_to 'Reply', show_answer_path(user, @proyecto, question), class: 'btn btn btn-primary btn-xs' %>
                    </span>
                  </div>
                
              </div>
            </div>
          <% end %>  
        <% end %>
      <% end %>

      <% @posts_deliverable = false %>
      <% @questions.each do |question| %>
        <% @users.each do |user| %>
          <% if question.user_id == user.id && question.question_type == "deliverable" %>
            <% if @posts_deliverable == false %>
              <h3>Deliverables</h3>
              <% @posts_deliverable = true %>
            <% end %>
            <div class="status row">
              <div class="span7">
                  <strong><%= "#{user.name} #{user.last_name} " %></strong><small>says:</small>
                  <p><strong><small><%= question.title %></small></strong></p>
                  <p><small><em><%= question.question %></em></small></p>
                  <div class="meta">
                    <p><small><%= link_to time_ago_in_words(question.created_at) + " ago", show_answers_question_path(user, @proyecto, question) %>
                    <% if question.attachment_url %>
                      <%= link_to "Download", download_file_path(question), class: 'btn btn btn-info btn-xs' %>
                    <% end %>
                    </small>
                    <span>
                      <%= link_to 'Reply', show_answer_path(user, @proyecto, question), class: 'btn btn btn-primary btn-xs' %>
                    </span>
                  </div>

              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <div  class="row col-md-6 col-md-offset-9">
        <%= link_to 'New Post', new_proyecto_question_path(@proyecto), class: "btn btn-success" %>
      </div>
      <% if @posts_discussion == false && @posts_resource == false && @posts_deliverable == false %>
        <h1><small>There are no posts for <%= @proyecto.title %></small></h1>
      <% end %>
      <%= will_paginate @questions, renderer: BootstrapPagination::Rails %>
    </div>
</div>
      	