config/routes.rb
Rails.application.routes.draw do
  
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  get '/logout', to: 'sessions#logout', as: 'logout'

  get '/signin', to: 'sessions#sign_in_form', as: 'sign_in_form'

  post '/signin', to: 'sessions#signin', as: 'signin'

  get '/user/:user_id/proyecto/:proyecto_id/questions/:id/answer/new', to: 'answers#new', as: 'show_answer'
  
  get '/collaboration/collaboration', as: 'collaboration'

  get '/proyecto/:id/collaboration/collaboration', to: 'collaboration#collaboration', as: 'show_collaboration_space'

  get '/proyecto/:proyecto_id/collaboration/collaboration', to:'collaboration#collaboration', as: 'back_collaboration_space'
  get '/user/:user_id/proyecto/:proyecto_id/questions/:id/collaboration/collaboration', to: 'collaboration#answers_question', as: 'show_answers_question'

  get '/proyecto/:id/users/show', to: 'postulations#create', as: 'request'

  get '/proyectos/new', to: 'proyectos#new', as: 'new_project'
 
  get '/proyectos/:id', to: 'proyectos#show', as: 'description_project'

   get '/proyecto/:id/users/:user_id/practicantes/show', to: 'postulations#update', as: 'update_request'

  get '/proyecto/:id/practicantes/show', to: 'practicantes#show', as: 'show_participantes_proyecto'

  get '/user/:id/perfil/practicante', to: 'practicantes#profile', as: 'perfil_pract'

  get '/proyecto/:id/practicantes/show', to: 'practicantes#back', as: 'back_participantes_proyecto'

  get '/question/:id/collaboration/collaboration', to: 'collaboration#download_file', as: 'download_file'

  
  resources :users
  resources :skills
  resources :proyectos
  resources :answers
 
  
  resources :proyectos do
    resources :questions
  end

  resources :questions do
      resources :answers
    end

  root 'sessions#home'
  
  Letscode::Application.routes.draw do
   resources :questions, only: [:index, :new, :create, :destroy]
  end
  

end

app/controllers/practicantes_controller.rb
class PracticantesController < ApplicationController

	def show
	  @users = User.all
	  @proyecto = Proyecto.find(params[:id])
	  @postulations = Postulation.where(proyecto_id: @proyecto.id)
	end


	def profile
      @user = User.find(params[:id])
      render :'perfil/practicante'
  end

	def back
		# render :'proyectos/:proyectos_id/practicantes_show'

	end
end

app/views/practicantes/show.html.erb
<div class="row col-md-12">
 	<div class="row col-md-8 col-md-offset-3">
	 	<p id="notice"><%= notice %></p>




			<div class="page-header">
			  <h1>Welcome <%= current_user.name %></h1>
			</div>
			<h3><%= @proyecto.title %></h3>
			<p><%= link_to 'Project Description', description_project_path, class: "btn btn-success"  %></p>

<br>
			<h3 class="h3">Learners by Project</h3>
	</div>

	<div class="row col-md-10 col-md-offset-1">
			
			    <table class="table table-hover">
					<thead>
						<tr>
							<th>Name of Learner</th>
							<th>Last Name</th>
							<th>Status</th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<tbody>
		        <% @users.each do |user| %>
		            
						  <% @postulations.each do |postulation|  %>
							  <tr>
							  <% if postulation.user_id == user.id %>
							      <% project = current_project(postulation.proyecto_id) %>
							      <% @find = true %>

							      <!-- MODIFICATION -->
								  <td><%= link_to user.name, perfil_pract_path(user) %></td>
								  <!-- MODIFICATION -->

								  <td><%= user.last_name %></td>
								  <% if postulation.status == "aceptado" %>
								    <td><span class="label label-success">Accepted</h1></td>
								  <% end %>
								  <% if  postulation.status == "postulado" %>
								    <td><span class="label label-warning">Applied</span></td>
								    <td><%= link_to 'Accept Learner', update_request_path(postulation.proyecto_id, user), class: 'btn btn-danger btn-sm' %></td>
								  <% end %>
							  <% end %>
							  </tr> 
							<% end %>
							
						<% end %>		
					</tbody>
				</table>
	</div>
		<div class="col-md-10 col-md-offset-3">
			<br><br><br><br>
		<div><%= link_to 'Back', user_path(current_user) %></div>
</div>