config/routes.rb
Rails.application.routes.draw do
  
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  get '/logout', to: 'sessions#logout', as: 'logout'

  get '/signin', to: 'sessions#sign_in_form', as: 'sign_in_form'

  post '/signin', to: 'sessions#signin', as: 'signin'

  get '/user/:user_id/proyecto/:proyecto_id/questions/:id/answer/new', to: 'answers#new', as: 'show_answer'
  
  get '/collaboration/collaboration', as: 'collaboration'

  get '/proyecto/:id/collaboration/collaboration', to: 'collaboration#collaboration', as: 'show_collaboration_space'

  get '/proyecto/:proyecto_id/collaboration/collaboration', to:'collaboration#collaboration', as: 'back_collaboration_space'
  get '/user/:user_id/proyecto/:proyecto_id/questions/:id/collaboration/collaboration', to: 'collaboration#answers_question', as: 'show_answers_question'

  get '/proyecto/:id/users/show', to: 'postulations#create', as: 'request'

  get '/proyectos/new', to: 'proyectos#new', as: 'new_project'
 
  get '/proyectos/:id', to: 'proyectos#show', as: 'description_project'

   get '/proyecto/:id/users/:user_id/practicantes/show', to: 'postulations#update', as: 'update_request'

  get '/proyecto/:id/practicantes/show', to: 'practicantes#show', as: 'show_participantes_proyecto'

  get '/user/:id/perfil/practicante', to: 'practicantes#profile', as: 'perfil_pract'

  get '/proyecto/:id/practicantes/show', to: 'practicantes#back', as: 'back_participantes_proyecto'

  get '/question/:id/collaboration/collaboration', to: 'collaboration#download_file', as: 'download_file'

  
  resources :users
  resources :skills
  resources :proyectos
  resources :answers
 
  
  resources :proyectos do
    resources :questions
  end

  resources :questions do
      resources :answers
    end

  root 'sessions#home'
  
  Letscode::Application.routes.draw do
   resources :questions, only: [:index, :new, :create, :destroy]
  end
  

end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
	include BCrypt
	validates :email, presence: true, uniqueness: true

  has_many :questions
  has_many :questions_answered, :foreign_key => :responder_id, :class_name => "Answer"
  has_many :proyectos_created, :foreign_key => :empresa_id, :class_name => "Proyecto"
  has_many :answers, through: :questions
  #has_many :proskills, through: :proyectos
  has_many :postulations
  has_many :userskills
  has_many :proyectos
  has_many :skills, through: :userskills
  accepts_nested_attributes_for :skills
  has_secure_password





  def status_of_project(project)
    postulation = self.postulations.where(proyecto_id:project.id)
    postulation.first.status
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end
  
  # GET /users/1
  # GET /users/1.json
  def show
    # @user = User.find(params[:id])
  end


  def new
    @user_type = params[:user_type]
    @register = params[:register]
    @user = User.new
  end

  # GET /users/new
  def new1
    @user = User.new
  end

  def new2
    @user = User.new
  end
 
  # POST /users
  # POST /users.json
  def create
    p '*' * 50 
    p params
    @user = User.new(user_params)

    params[:user][:skill_ids] ||= []
    skills = params[:user][:skill_ids]

    respond_to do |format|
      if @user.save
          skills.each do |skill|
            @userskills = Userskill.new(skill_id: skill, user_id: @user.id)
            @userskills.save
          end
        format.html { redirect_to '/signin', notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # GET /users/1/edit

	def edit
    @user = User.find(session[:user_id])
    @user_type = @user.user_type
	end

  #PUT /users/1
  def update

     @user = User.find(session[:user_id])
     @user.userskills

     p params[:user][:skill_ids] ||= []

     skills = params[:user][:skill_ids]
    
    respond_to do |format|
      if @user.update(user_params)
          skills.each do |skill|
            @userskills = Userskill.new(skill_id: skill, user_id: @user.id)
            @userskills.save
          end
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user_id = @user.id
    @user.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :last_name, :email, :genre, :birthday_year, :opinion, :organization, :password, :user_type)
    end

end

app/views/users/_form.html.erb
<% if user_type == "Empresario" || user_type == "empresa" %>
  <% user_type = "empresa" %>
  <% @user_value = "emp" %>
<% else %>
  <% user_type = "practicante" %>
  <% @user_value = "prac" %>
<% end %>


<%if @user_value == "prac" && @register == "Update" %>
    <h1 id="hsign"><%= "#{user_type.capitalize}, registrate." %></h1>
<% elsif @user_value == "emp" && @register == "Update"  %>
    <h1 id="hsign"><%= "#{user_type.capitalize}, registrate." %></h1>
<% else %>
    <h1 id="hsign">Update your Profile</h1>
<% end %>

<br>
<hr>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved: </h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="content_profile">
    <div>
        <div>
          
          <%= f.text_field :name, placeholder: 'name', class: 'form-control' %><br>
        </div>

        <div class="field">
          <%= f.text_field :last_name, placeholder: 'last_name', class: 'form-control' %><br>
        </div>

        <div class="field">
       
          <%= f.text_field :genre, placeholder: 'genre', class: 'form-control' %><br>
        </div>

        <div class="field">
       
            <%= f.text_field :email, placeholder: 'email', class: 'form-control' %><br>
        </div>

        <div class="field">
       
          <%= f.text_field :birthday_year, placeholder: 'birthyear', class: 'form-control' %><br>
        </div>

        <% if @user_value == "emp" %>
          
          <div class="field">

            <%= f.text_field :organization, placeholder: 'organization', class: 'form-control' %>      <br>
          </div>
        <% end %> 

        <div class="field">

          <%= f.text_field :opinion, placeholder: 'opinion', class: 'form-control' %>
        </div>      <br>

        <div class="hide">
          <%= f.label :user_type %><br>
          <%= f.text_field :user_type, :value => user_type, :disabled => false%>
        </div>

         <div class="field">

          <%= f.password_field :password, placeholder: 'password', class: 'form-control' %>
        </div><br>


          <% if @user_value == "prac" %>
         
            <div class="checkbox" >
             
              <%= "Your Skills:" %>
              
              <% Skill.all.each do |skill| %>
              <li><%= check_box_tag "user[skill_ids][]", skill.id, @user.skills.include?(skill) %><%= skill.name %></li>
              <%end%>
               <br>
            </div> 

          <% end %>

          
          <div class="controls">
            <%= f.submit 'Update Profile', class: 'btn btn-primary'%>
          </div>
      <% end %>
     </div>
</div>

app/views/users/_form2.html.erb
<%= link_to 'Sign in', sign_in_form_path %> 
<h1>Practicante, registrate.</h1>


<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved: </h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="signup">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>

    <div class="field">
      <%= f.label :genre %><br>
      <%= f.text_field :genre %>
    </div>

    <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :birthday_year %><br>
      <%= f.text_field :birthday_year %>
    </div>

    <div class="field">
      <%= f.label :opinion %><br>
      <%= f.text_field :opinion %>
    </div>

    <div class="hide">
      <%= f.label :user_type %><br>
      <%= f.text_field :user_type, :value => 'Practicante', :disabled => false%>
    </div>

     <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div><br>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/users/destroy.js.erb
$('#delete_user_<%= @user_id %>').closest('tr').fadeOut();

app/views/users/edit.html.erb
<div class="row col-md-6 col-md-offset-4">

</div>
<div class="row col-md-6 col-md-offset-4">
<%= render 'form', user_type: @user_type %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		  <tr id="<%= "delete_user_#{user.id}" %>">
		  	<td><%= user.name %></td>
		  	<td><%= user.email %></td>
		  	<td><%= link_to 'Show', user %></td>
		  	<td><%= link_to 'Edit', edit_user_path(user) %></td>
		  	<td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %></td>
		  </tr>
		<% end %>
	</tbody>
</table>

<br>

app/views/users/new.html.erb
<div class="row col-md-4 col-md-offset-4">
<%= render 'form', user_type: @user_type %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<div  class="col-xs-12 col-xs-offset-0 col-sm-12 col-sm-offset-0 col-md-12 col-md-offset-0 col-lg-3 col-lg-offset-2">
  <div class="content">
	<div class="page-header">
	  <h1>Welcome <%= current_user.name %></h1>
	</div>
	<br>
	<% if current_user.user_type == "empresa" %>
	<h3 id="your">YOUR PROJECTS</h3>

	<% else %>
	<h3 id="all">ALL PROJECTS:</h3>
	<% end %>
	<br>
	<div class="media">
	  <div class="media-body">
		<% if current_user.user_type == "practicante" %>
			
		    <table class="table table-hover">
				<thead>
					<tr>
						<th>Project Title</th>
						<th>Project Status</th>
						<th>Collaboration Space</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>

	        <% all_projects.each do |project| %>
              <% @find = false %>
                <tr>
				  <% current_user.postulations.each do |postulation|  %>
					  <% if postulation.proyecto_id == project.id && current_user.id == postulation.user_id %>
					     <% @find = true %>
				         <!-- working -->
					     <td><%= link_to project.title, description_project_path(project) %></td>
					     <!-- worked -->
					     <% if postulation.status == "aceptado" %>
						    <td><span class="label label-success">Accepted</span></td>
						    <td><%= link_to 'Collaborate', show_collaboration_space_path(project), class: 'btn btn-success btn-sm' %></td>
						 <% end %>
						 <% if postulation.status == "postulado" %>
						    <td><span class="label label-warning">Processing</span></td>
						    <td><button type="button" class="btn btn-warning btn-sm" disabled="true"><%= "Applied" %></button></td>
						  <% end %>
					  <% end %>
				  <% end %><!-- postulations -->	
					<% if @find == false %>
						<td><%= link_to project.title, description_project_path(project) %></td>
						<td><span class="label label-danger">Available</span></td>
						<td><%= link_to ' Join ', request_path(project),class: "btn btn-danger btn-sm" %></td>	
					<% end %>
				</tr>
			<% end %><!-- projects -->		
			</tbody>
			</table>
			
		<% else %>
            <% if current_user.proyectos.count != 0 %>
			  <table class="table table-hover">
				<thead>
					<tr>
						<th>Project Title</th>
						<th>Project Description</th>
						<th>Incentive</th>
						<th>Project Result</th>
						<th>Students Accepted</th>
						<th>Project Deadline</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
				<% current_user.proyectos.each do |proyecto| %>
				  <tr id="<%= "delete_proyecto_#{proyecto.id}" %>">
				  	<td><%= link_to proyecto.title, show_collaboration_space_path(proyecto) %></td>
				  	<td><%= proyecto.description %></td>
				  	<td><%= proyecto.incentive %></td>
				  	<td><%= proyecto.result %></td>
				  	<td><%= proyecto.num_students %></td>
				  	<td><%= proyecto.dead_line %></td>
				  	<td><%= link_to 'Learners by Project', show_participantes_proyecto_path(proyecto), class: 'btn  btn-primary btn-sm' %></td>
				  	<td><%= link_to 'Edit', edit_proyecto_path(proyecto), class: 'btn btn-success btn-sm' %></td>
				  	<td><%= link_to 'Destroy', proyecto, method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure?' }, :remote => true %></td>
				  </tr>
				<% end %>
			    </tbody>
		      </table>
		    </div></div>
		    <% else %>
		      <h3>There are no projects</h3>
		    <% end %>
	   <% end %>   
	<br><br><br><br>
	<div  class="col-xs-12 col-xs-offset-0 col-sm-12 col-sm-offset-0 col-md-12 col-md-offset-0 col-lg-3 col-lg-offset-2">
		<% if current_user.user_type == "empresa" %>
		  <p><%= link_to 'New Project', new_project_path, class: "btn btn-success"  %></p>
		<% end %>
	</div>
  </div>
</div>