config/routes.rb
Rails.application.routes.draw do
  
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  get '/logout', to: 'sessions#logout', as: 'logout'

  get '/signin', to: 'sessions#sign_in_form', as: 'sign_in_form'

  post '/signin', to: 'sessions#signin', as: 'signin'

  get '/user/:user_id/proyecto/:proyecto_id/questions/:id/answer/new', to: 'answers#new', as: 'show_answer'
  
  get '/collaboration/collaboration', as: 'collaboration'

  get '/proyecto/:id/collaboration/collaboration', to: 'collaboration#collaboration', as: 'show_collaboration_space'

  get '/proyecto/:proyecto_id/collaboration/collaboration', to:'collaboration#collaboration', as: 'back_collaboration_space'
  get '/user/:user_id/proyecto/:proyecto_id/questions/:id/collaboration/collaboration', to: 'collaboration#answers_question', as: 'show_answers_question'

  get '/proyecto/:id/users/show', to: 'postulations#create', as: 'request'

  get '/proyectos/new', to: 'proyectos#new', as: 'new_project'
 
  get '/proyectos/:id', to: 'proyectos#show', as: 'description_project'

   get '/proyecto/:id/users/:user_id/practicantes/show', to: 'postulations#update', as: 'update_request'

  get '/proyecto/:id/practicantes/show', to: 'practicantes#show', as: 'show_participantes_proyecto'

  get '/user/:id/perfil/practicante', to: 'practicantes#profile', as: 'perfil_pract'

  get '/proyecto/:id/practicantes/show', to: 'practicantes#back', as: 'back_participantes_proyecto'

  get '/question/:id/collaboration/collaboration', to: 'collaboration#download_file', as: 'download_file'

  
  resources :users
  resources :skills
  resources :proyectos
  resources :answers
 
  
  resources :proyectos do
    resources :questions
  end

  resources :questions do
      resources :answers
    end

  root 'sessions#home'
  
  Letscode::Application.routes.draw do
   resources :questions, only: [:index, :new, :create, :destroy]
  end
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Welcome | Let's Code" %></title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <ul id="title" class="nav navbar-nav">
      <li><%= link_to 'Let´s Code!', root_path %></li>
      </ul>
      <!-- RESOURCE -->
      <% if current_user %>
      <!-- RESOURCE! -->
      <div id="btn" class="btn-group pull-right right-nav">
        <button type="button" class="btn btn-primary dropdown-toggle" id="button">
          <a class="dropdown-toggle"><%= current_user.name %></a>
        </button>
        <button id="button" type="button" data-toggle="dropdown" class="btn btn-primary dropdown-toggle"><span class="caret"></span></button>
        <!-- MODIFICATION -->
        <ul class="dropdown-menu">
          <li><%= link_to 'Dashboard', user_path(current_user) %></li>
          <li><%= link_to 'Profile', edit_user_path(current_user) %></li>
          <li><%= link_to 'Sign Out', logout_path %></li>
        </ul>
        <!-- MODIFICATION -->
      </div>
      <% else %>
      <ul id="signin" class="nav navbar-nav">
      <li><%= link_to 'Sign In', signin_path %></li>
     </ul>
      <% end %>
    </nav>
   <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
   <% elsif flash[:error] %>
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div> 
   <% elsif flash[:alert] %>
    <div class="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div> 
   <% end %>  
   <!-- <div class="top"> -->
     <%= yield %>
   <!-- </div> -->


  </div>


   

</div>
</body>
</html>